name: CI

on: [push]
jobs:
  build-test: # 2 espaços (Correto)
    runs-on: ubuntu-22.04 # 4 espaços (Correto)
    steps: # 4 espaços (Correto)
    
      - name: Checkout # 6 espaços (Correto)
        uses: actions/checkout@v3

      - name: Setup Node.js # 6 espaços (Correto)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 10 espaços (Correto)

      - name: Instalar Dependências
        run: npm install

      - name: Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          install-cypress: true
          build: 'npm run build'
          start: 'npm run dev'

      - name: Upload Artifacts # 6 espaços (Novo passo, alinhado com os outros -name:)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress Result
          path: |
            cypress/screenshots # Alinhado corretamente com 'path'
            cypress/videos
            cypress/results
          if-no-files-found: ignore